title: Matt Ronchetto — doamatto
description: I'm a high school student living in San Diego. I like to mess around with software development and graphic design.
url: https://maatt.fr
baseurl: ""
permalink: pretty
timezone: 'America/Los_Angeles'

exclude:
  - LICENSE
  - TODO.txt

ignore_theme_config: true
encoding: 'utf-8'
safe: true
strict_front_matter: true
markdown_ext: 'md'
encoding: 'utf-8'

collections:
  root:
    relative_directory: '_pages/'
    output: true
    permalink: /:path.html

# build
show_drafts: false
profile: true
liquid:
  error_mode: strict
  strict_variables: true
  strict_filters: true

# serve
port: 10000
