# The URL the site will be built for
base_url = "https://www.doamatto.xyz"

title = "Matt Ronchetto - doamatto"

default_language = "en"

compile_sass = false
minify_html = true

generate_feed = true
feed_filename = "atom.xml"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
highlight_code = false
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true

[extra]
# Put all your custom variables here
