base_url = "https://www.doamatto.xyz"

title = "Matt Ronchetto - doamatto"
description = ""

default_language = "en"

compile_sass = false
minify_html = true

generate_feed = true
feed_filename = "atom.xml"

build_search_index = false

[markdown]
highlight_code = false
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true

[extra]
# Put all your custom variables here
