base_url= "https://maatt.fr"
default_language= "en"
compile_sass= true
ignored_content= ["**/.DS_Store"]

[markdown]
render_emoji= true
external_links_target_blank= false
external_links_no_follow= true
external_links_no_referrer= true

[link_checker]
internal_level= "warn"
external_level= "warn"
