base_url = "https://www.doamatto.xyz"

title = "Matt Ronchetto - doamatto"
description = "Salut, I'm Matt Ronchetto. I'm a high school student in San Diego, CA that enjoys programming, writing, and way too many other things to count."

default_language = "en"

compile_sass = true
minify_html = false
output_dir = "out"

generate_feed = true
feed_filename = "atom.xml"

build_search_index = false

[markdown]
highlight_code = false
render_emoji = true
external_links_target_blank = true

[extra]
author = "doamatto"
ogimage = "/android-chrome-192x192.png"
