baseURL = "https://maatt.fr"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
languageCode = "en"
removePathAccents = true
timeZone = "UTC"
uglyURLs = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
