baseURL = "https://testing.doamatto.xyz/"
languageCode = "en-uk"
title = "doamatto"
contentDir = "content"

canonifyURLs = true
relativeURLs = true

DefaultContentLanguage = "en"

[markup]
  defaultMarkdownHandler = "blackfriday"

[Permalinks]
  posts = "/posts/:filename/"

[languages]
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 1
    [[languages.en.menu.nav]]
      url = "/about"
      name = "About"
      weight = 1
    [[languages.en.menu.nav]]
      url = "/projects"
      name = "Projects"
      weight = 2
    [[languages.en.menu.nav]]
      url = "/contact"
      name = "Contact"
      weight = 3

    [[languages.en.menu.foot]]
      url = "/imprint"
      name = "Imprint."
      weight = 1
    [[languages.en.menu.foot]]
      url = "/privacy"
      name = "Privacy."
      weight = 2
    [[languages.en.menu.foot]]
      url = "/sitemap"
      name = "Sitemap."
      weight = 1
  [languages.fr]
    languageCode = "fr"
    languageName = "Français"
    weight = 1
    [[languages.fr.menu.nav]]
      url = "/a-propos"
      name = "À propos"
      weight = 1
    [[languages.fr.menu.nav]]
      url = "/projets"
      name = "Projets"
      weight = 2
    [[languages.fr.menu.nav]]
      url = "/contact"
      name = "Contact"
      weight = 3

    [[languages.fr.menu.foot]]
      url = "/mentions-legales"
      name = "Mentions légales."
      weight = 1
    [[languages.fr.menu.foot]]
      url = "/confidentialite"
      name = "Confidentialité."
      weight = 2
    [[languages.fr.menu.foot]]
      url = "/carte-du-site"
      name = "Carte du site."
      weight = 1

[Params]
  author = "doamatto"
  favicon = "assets/logo.svg"
  logo = "assets/logo.svg"