baseURL = "https://maatt.fr"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
languageCode = "en"
removePathAccents = true
timeZone = "UTC"

[markup]
  [marukup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Needed for <br/> in documents.

[params]
  mainSections = [ "blog" ]

[permalinks]
  blog = "/blog/:filename/"
  page = "/:filename/"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
