---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
upload_dir: static/assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: out
  preview_docker_image: balthek/zola:0.14.0
  mount_path: public
  working_dir: "/srv"
  instant_preview_command: docker run -u "$(id -u):$(id -g)" -v $PWD:/app --workdir
    /app -p 8080:8080 -p 1024:1024 balthek/zola:0.14.0 serve --interface 0.0.0.0 --port
    8080 --base-url localhost
