name: Zola site build
on: 
  push:
    branches:
      - master 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build with Zola
      uses: shalzz/zola-deploy-action@master
      env:
        BUILD_ONLY: true